name: Compile udah_mod Files
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-8.1.3-sdk.tar.bz2
          
      - name: Compile Specific Files
        run: |
          # Buat struktur folder sementara
          mkdir -p temp_game/game
          
          # Salin file yang ingin dikompilasi
          cp udah_mod/{x-script.rpy,x-script_nts.rpy} temp_game/game/
          
          # Kompilasi
          ./renpy-8.1.3-sdk/renpy.sh temp_game compile
          
          # Pindahkan hasil ke udah_mod
          mv temp_game/game/*.rpyc udah_mod/
          
      - uses: actions/upload-artifact@v4
        with:
          name: Compiled-Files
          path: udah_mod/*.rpyc
