name: Compile Ren'Py
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Project Structure
        run: |
          mkdir -p game
          cp udah_mod/*.rpy game/
          
      - name: Install Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-8.1.3-sdk.tar.bz2
          
      - name: Compile Scripts
        run: |
          ./renpy-8.1.3-sdk/renpy.sh ./ compile
          
      - name: Move Results
        run: |
          mkdir -p udah_mod_compiled
          mv game/*.rpyc udah_mod_compiled/
          
      - uses: actions/upload-artifact@v4
        with:
          name: Compiled-RPYC
          path: udah_mod_compiled/*.rpyc
