name: Compile udah_mod Files
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-8.1.3-sdk.tar.bz2
          
      - name: Compile Files
        run: |
          # Buat struktur project Ren'Py
          mkdir -p game
          cp udah_mod/{x-script.rpy,x-script_nts.rpy} game/
          
          # Kompilasi
          ./renpy-8.1.3-sdk/renpy.sh ./ compile
          
          # Pindahkan hasil ke udah_mod dan pertahankan nama
          mv game/x-script.rpyc udah_mod/
          mv game/x-script_nts.rpyc udah_mod/
          
          # Verifikasi
          ls -lh udah_mod/*.rpyc
          
      - uses: actions/upload-artifact@v4
        with:
          name: Compiled-Files
          path: udah_mod/*.rpyc
