name: Compile Ren'Py
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ren'Py
        run: |
          wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
          tar -xf renpy-8.1.3-sdk.tar.bz2
      - name: Compile Scripts
        run: |
          ./renpy-8.1.3-sdk/renpy.sh ./game compile
      - uses: actions/upload-artifact@v3
        with:
          name: Compiled-RPYC
          path: game/game/*.rpyc